### ISSUE TITLE
Consumer List shows the wrong key

### ISSUE THREAD

**Issue by NKjoep** [EntandoOldVersions/entando-core-engine#4]
In the Consumer List, the table of the results is showing the "secret" value when was supposed to report the "key" of the consumer.

**Comment by NKjoep** [comment]
Update: the problem seems to be in the dao...

**Comment by eugeniosant** [comment]
Thanks Andrea. Bug fixed with commit f880b6f3448bcdab1b3a63de6703382e323bac3c
